### ISSUE TITLE
Allow to export/import additional properties

### ISSUE THREAD

**Issue by drallgood** [mAAdhaTTah/wordpress-github-sync#106]
I'd like to export & import additonal data, e.g. additonal info for custom post types. 
What I'm trying to do is to handle all the information necessary for a podlove episode, but they are storing additional information in a separate object. 

So far, I've been able to export the necessary information by implementing a function for the 'wpghs_post_meta' filter. However I'm struggling to find a good place to write the information back when importing the post. 

It would be good, to have another hook/filter that allows me to read the meta array before the post gets updated with the information stored in the header of the post.

**Comment by mAAdhaTTah** [comment]
Yeah, so this is kind of an interesting problem. Unfortunately, #107 isn't going to solve it; what you want to be able to do is divert information that would have been saved into post_meta to someplace else. If that's correct, I'll need to think a bit more about how to solve that.

I'm hoping to wrap the work on the major rewrite (#98) this weekend; once that's complete, I'll look into this. That PR introduces a new DB class, which is probably where this action/filter would have to be included. I'll have to think through how to make this work exactly, though.

Thanks for the idea.

**Comment by drallgood** [comment]
ok. I wasn't 100% convinced this was the right solution either...

Maybe you have a better idea how to solve this. I'm eagerly awaiting your ideas :smile: 
Thanks for your time!

**Comment by mAAdhaTTah** [comment]
@drallgood This is part of the `1.4.0` release. Use `wpghs_pre_import_meta`; see the [wiki](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress----GitHub-Sync) for documentation.
