### ISSUE TITLE
Can this work with custom post types?

### ISSUE THREAD

**Issue by actuallymentor** [mAAdhaTTah/wordpress-github-sync#117]
Great plugin :+1: 

I work with LearnDash LMS for my school and would love to allow students to do pull requests etc on the content. Right now however the plugin doesn't recognise those...

**Comment by mAAdhaTTah** [comment]
Yes, we support custom post types, see [here](https://github.com/mAAdhaTTah/wordpress-github-sync#custom-post-type--status-support).

**Comment by actuallymentor** [comment]
Overlooked that, apologies :)

It's not working for me though, I'm currently using:

add_filter('wpghs_whitelisted_post_types', function ($supported_post_types) {
  return array_merge($supported_post_types, array(
    // add your custom post types here
    'sfwd-courses',
    'sfwd-lessons',
    'sfwd-topic',
    'sfwd-quiz'
  ));
});

This is the way right?

**Comment by mAAdhaTTah** [comment]
Yes, that looks correct. Just note the post will get exported if it matches both the whitelisted post_type as well as post_status (`publish`).

**Comment by mAAdhaTTah** [comment]
@actuallymentor Did you get this working?

**Comment by mAAdhaTTah** [comment]
Closing for now. Feel free to reopen if you're still having issues.
