### ISSUE TITLE
HTML showing as code in the backend

### ISSUE THREAD

**Issue by actuallymentor** [mAAdhaTTah/wordpress-github-sync#118]
![2015-11-20 07_27_53-wordpress github sync id elearning wordpress](https://cloud.githubusercontent.com/assets/9071382/11293226/53970866-8f58-11e5-8a0f-d7b3d3e06324.png)

**Comment by mAAdhaTTah** [comment]
Whoops, got overzealous with the escaping. Thanks for flagging!
