### ISSUE TITLE
Can user set a special "_wpghs_github_path"?

### ISSUE THREAD

**Issue by malsony** [mAAdhaTTah/wordpress-github-sync#119]
I tried to find whether there is a setting for the GitHub location of posts, as bloggers and webmasters might want to set a special path for each post, but I could find anyway to do so. Will you consider adding this "Customized GitHub Path" in future?

I tried to change the `_wpghs_github_path` meta value in the database for a post, of which the GitHub path has been changed, and then updated the post in WordPress, but later I found the post existing in "_posts/DATE_POSTNAME" on GitHub side, so I need to update it again if I want to move it to the desired path.

**Comment by mAAdhaTTah** [comment]
Don't modify that value in the database; that just keeps track of what the path was when the file was exported. Changing that could make it difficult for match up imported posts (if the sha fails).

There are a couple filters that will do what you're looking for: [`wpghs_directory_published`](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress-GitHub-Sync-with-Filters#wpghs_directory_published), [`wpghs_directory_unpublished`](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress-GitHub-Sync-with-Filters#wpghs_directory_unpublished), and [`wpghs_filename`](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress-GitHub-Sync-with-Filters#wpghs_filename). Let me know if any of the instructions in the wiki aren't clear.

**Comment by malsony** [comment]
I am reading it and try to find how to customize it (I have no idea what your codes mean, but I will try). I have more than one user in a WordPress site and I want to WPGHS only sync a specific user's posts or pages, and/or some post_meta tags, is it possible to do so? Thanks!

**Comment by malsony** [comment]
Read the wiki and README, but still got no clue how and where to put the filters... :joy: Maybe this thread can be merged with #120 .

**Comment by mAAdhaTTah** [comment]
It is; you'll be able to customize the functionality of the plugin using WordPress [Filters](https://codex.wordpress.org/Plugin_API/Filter_Reference). The plugin makes those filter hooks available to customize. You (and him) are right though; the documentation could use some work. I had originally built this plugin assuming it was going to be used primarily for developers. Now that it's not

It's not possible to just sync a particular user's posts, though I could add a filter that makes that possible.

**Comment by malsony** [comment]
:sob: Can I follow the [README](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/README.md#custom-post-type--status-support), and, create a file `wp-content/mu-plugins/wpghs-custom-filters.php`?

:joy: But not sure how to pass a certain author using the code at the moment...

**Comment by mAAdhaTTah** [comment]
1. Can and should!

2. It's not possible yet.

**Comment by mAAdhaTTah** [comment]
@malsony The two added filters provide control over what posts are supported. You can use them to select only a single author for import/export. You can add a query args to the mass export to only get that author, and you can filter the post by author.

Obviously, this needs to be documented so you can use it. If you haven't already, definitely familiarize yourself with WordPress' action/filter hooks system. WPGHS uses the same system for customization. I suggest the file in `mu-plugins` in the README, as you've found. I'll eventually spend some time on filling out the [wiki](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki).
