### ISSUE TITLE
Import from GitHub Always Returns "Semaphore Locked"

### ISSUE THREAD

**Issue by mAAdhaTTah** [mAAdhaTTah/wordpress-github-sync#121]
Maybe? I got this when importing a new post after a PR got merged. It was also mentioned in another issue.

**Comment by BoweFrankema** [comment]
I'm having the same issue. Import/Export seems to be not working anymore since 4.4. Sadly don't have any other additional errors/info

**Comment by mAAdhaTTah** [comment]
Part of the problem is I don't have a solid way to fully integration test the plugin together with the GitHub API. I'll have to take a closer look at whether that's possible.

**Comment by benbalter** [comment]
I think I might be running into the same issue? Clicking "import" simply reloads the page, with no feedback message on 4.4.1. 

> I don't have a solid way to fully integration test the plugin together with the GitHub API.

I don't know testing in the PHP world as well anymore, but in the Ruby world, I use Webmock often, which can intercept HTTP calls, and return a cached response (along with VCR). It looks like https://github.com/php-vcr/php-vcr might work?

**Comment by mAAdhaTTah** [comment]
I haven't tested on 4.4 yet. I wonder if there's something specific about the new version that's breaking thoughts? Though I have had this issue on 4.3, so maybe not. I have to spend some time digging into this. The Semaphore may be causing a lot of these issues, so maybe I messed that up somewhere.

@benbalter Is an integration tests against the live GitHub API using a test repository possible or would the GitHub API cut us off?

**Comment by benbalter** [comment]
> @benbalter Is an integration tests against the live GitHub API using a test repository possible or would the GitHub API cut us off?

Possible, yes. You'd have to provide Travis with an encrypted token to make the write calls (and to get around rate limits), and document how to do the same locally, but no :red_circle: :flags:s. The creds would get you 5k requests an hour, which I suspect would be fine given the rate of development in the repo.

**Comment by mAAdhaTTah** [comment]
> I think I might be running into the same issue? Clicking "import" simply reloads the page, with no feedback message on 4.4.1.

Can confirm this issue, but I believe this is an unrelated bug. Follow #127 for that one.
