### ISSUE TITLE
Import from GitHub does not parse Markdown

### ISSUE THREAD

**Issue by joshkoenig** [mAAdhaTTah/wordpress-github-sync#123]
First of all, thanks for creating this awesome plugin. Fine work!

I'm working on using this for a fun project where I want to have a set of Pages that are canonically tracked in GitHub so that changes can go through a more robust Pull Request collaboration workflow.

However, when importing changes from the repository, WordPress doesn't appear to be processing the Markdown. I get output like the following:

![screen shot 2015-12-21 at 6 39 26 pm](https://cloud.githubusercontent.com/assets/143186/11946701/33f26a6e-a812-11e5-94b1-b834395010bf.png)

From this file on GitHub:

https://github.com/joshkoenig/wordpress-at-scale/blob/495c0886ba5d6db105721630dfbe823378d93169/_pages/contributors.md

**Comment by joshkoenig** [comment]
Nevermind. It's covered in the README.

RTFM.

**Comment by mAAdhaTTah** [comment]
:+1:
