### ISSUE TITLE
Saving post with code snippets in WordPress breaking code syntax in github

### ISSUE THREAD

**Issue by DavidWells** [mAAdhaTTah/wordpress-github-sync#126]
Updating a post from within Wordpress is garbling quotes in code snippets.

```js
var hi = 'yo';

alert('hi');

```

becomes 

```js
var hi = &#039;yo&#039;;

alert(&#039;hi&#039;);
```

See: https://github.com/DavidWells/test-wp-sync/blob/e4bade87d50b77cbe8b5d8a7b84ac25870a0ced8/_posts/2016-01-16-mst-have-date-2.md

Where can I find the content being pushed back into github? 

Or how can I just store the raw markdown in the wordpress database the_content ?

Thanks for the cool plugin btw =)

**Comment by mAAdhaTTah** [comment]
What markdown plugin are you using?

**Comment by DavidWells** [comment]
This is happening with https://wordpress.org/plugins/jetpack-markdown/

I will give it a try with the other recommended plugin

**Comment by DavidWells** [comment]
The https://wordpress.org/plugins/wp-markdown/ messed up the code block immediately in Wordpress and in github.

![image](https://cloud.githubusercontent.com/assets/532272/12379211/6e2b9db0-bd0a-11e5-885e-1b68776861a8.png)

![image](https://cloud.githubusercontent.com/assets/532272/12379220/99144db0-bd0a-11e5-824e-0bf0ece72a10.png)

The JP markdown plugin is only messing up the code block when the post is resaved in WordPress admin.

Trying to track down the cause/

It looks like storing the raw HTML in the_content is adding some addition <br/> tags: 
![image](https://cloud.githubusercontent.com/assets/532272/12379245/07de6730-bd0b-11e5-913a-676632f3338e.png)

**Comment by mAAdhaTTah** [comment]
Oh, if WP-Markdown is messing up the input/output, there's not much we can do. I'll take a look and see if I can reproduce this myself. I still have to upgrade my personal site to 4.4.

**Comment by mAAdhaTTah** [comment]
Oh, sorry, WP-Markdown doesn't support fenced code blocks, so that won't work. Not sure what's going on with Jetpack Markdown.

**Comment by mAAdhaTTah** [comment]
I can reproduce this with JP Markdown. Investigating.

**Comment by mAAdhaTTah** [comment]
Maybe this one? https://github.com/Automattic/jetpack/issues/2068

In any case, this is with JP Markdown, as they're saving it to the DB this way.
