### ISSUE TITLE
Jetpack Markdown and Import Breakages

### ISSUE THREAD

**Issue by jakejackson1** [mAAdhaTTah/wordpress-github-sync#132]
Hi guys, 

I've been using the export feature of GitHub sync with Jetpack's markdown module and [this code snippet](https://github.com/mAAdhaTTah/wordpress-github-sync/issues/96) without any encoding problems on my development site. 

Recently I started testing the Import feature but noticed display/encoding problems which I haven't been able to resolve. For instance, when this [particular markdown is imported and saved](https://github.com/GravityPDF/v4-documentation/blob/master/_v4%20documentation/developer-backgrounds.md) The `Admin -> Stuff` code block converts the `>` to a `&gt;`, while the `<body>` tag is completely removed from the mark-up. 

I tracked the issue down to the kses validation that's applied during the wp_insert_post() but my knowledge of both the GitHub Sync and Jetpack Markdown modules aren't robust enough to track down what is going wrong. I have a feeling a particular filter that gets run during the normal post saving process doesn't get run when updating a post in GitHub Sync (because the issue doesn't occur during normal post saving in the admin area). 

If you have time to review the issue that would be great.

**Comment by mAAdhaTTah** [comment]
I'll take a look at this when I can, but I don't use Jetpack's Markdown module, so I don't know how much help I'll be.

**Comment by blueliquiddesigns** [comment]
Thanks!

**Comment by lite3** [comment]
I test it without any other plugin. It convert `>` to `&gt;`. and it will strip `<script>` code.

github code:

> \<script type="text/javascript">
> swfobject.embedSWF("http://www.litefeel.com/assets/album/album.swf", "flashalbum","100%","600","10.1.0","http://www.litefeel.com/assets/swf/expressInstall.swf", null, {allowFullscreen:true, base:"http://www.litefeel.com/assets/album/"});
> \</script>
> 
> \~~~
> Admin -> Stuff
> \~~~

github send to wordpress, it will convert to this:
**remove script tag and convert html tag**


> swfobject.embedSWF("http://www.litefeel.com/assets/album/album.swf", "flashalbum","100%","600","10.1.0","http://www.litefeel.com/assets/swf/expressInstall.swf", null, {allowFullscreen:true, base:"http://www.litefeel.com/assets/album/"});
> 
> 
> \~~~
> Admin -\&gt; Stuff
> \~~~

**Comment by mAAdhaTTah** [comment]
This should be fixed.
