### ISSUE TITLE
Use unique identifier to match posts to markdown files, not Post ID

### ISSUE THREAD

**Issue by kennyfraser** [mAAdhaTTah/wordpress-github-sync#133]
I am trying to implement this plugin to version content between environments. I have a development branch and a production ( master ) branch.

The idea is to deploy to production by merging development in to master. Since post ids are going to change from install to install, matching content by post id breaks this process.

My in-progress-solution is to generate a unique id ( uniqid() ) for each post and used that instead, Post ID is removed from meta to prevent merge conflicts.

**Comment by mAAdhaTTah** [comment]
How does WordPress know which post to update if it can't match my `post_id`?

**Comment by kennyfraser** [comment]
UID is saved as post meta. Instead of "update the post with post_id = id", I do "update the post with post meta UID = UID"

**Comment by mAAdhaTTah** [comment]
Punting on this, since the current setup is functional and hooks should be available to make this feasible to happen through a plugin. If not, PR is welcome, but this isn't going to land in core.
