### ISSUE TITLE
WordPress GitHub Sync Extra Plugin

### ISSUE THREAD

**Issue by kennyfraser** [mAAdhaTTah/wordpress-github-sync#135]
I have been working on implementing WordPress GitHub Sync for several projects at Mesosphere.

I tried to package the extra functionality required into a separate plugin ( Here: https://github.com/kennyfraser/wp-github-sync-extra ), but ended up heavily modifying the original as well. ( Here: https://github.com/kennyfraser/wordpress-github-sync/commits/development ).

I wanted to share my code, but for now it's not in a state where it can be easily formatted to pull requests.

Please take a look at the code in both repos I have linked here and share your thoughts on the functionality I have added and what ( if anything ) could be merged back in to the WordPress GitHub Sync Plugin.

**Comment by mAAdhaTTah** [comment]
Interesting. This is very cool.

As I mentioned in a previous comment, I'm very open to changes required to make the plugin more extensible, to enable a plugin like `wp-github-sync-extra` to function, should someone require those things.

Whether we need to enable alternate content processors is something I'm not so sure about, just given the complexity of the plugin already, but I'm definitely open to seeing a PR for it and discussing the implementation.

I commented on 2 commits that I would also be happy to see land upstream. IRT the caching change, we would just want to ensure BC by fetching from the blob by path + sha first and falling back to sha if that doesn't exist, then obviously doing the API call if it doesn't exist in both.

**Comment by mAAdhaTTah** [comment]
@kennyfraser If you want, I'd accept a PR to include information about your plugin. Are there any open changes you need to land upstream?

**Comment by mAAdhaTTah** [comment]
Feel free to reopen if you have things you need to land.
