### ISSUE TITLE
Override meta function from WordPress_GitHub_Sync_Post Class to add values to YAML Frontmatter

### ISSUE THREAD

**Issue by ibenot** [mAAdhaTTah/wordpress-github-sync#136]
Hi,
first of all thanks for this awesome plugin !
I just need to **override meta() function from WordPress_GitHub_Sync_Post in post.php** to add some custom meta and it works but I added my custom code after the published key like this :

```
'published'    => 'publish' === $this->status() ? true : false,
//add custom value
'myTag' => wp_get_post_terms($this->post->ID, 'myPostType', array("fields" => "names")),
```

[I followed this steps in your github wiki
](https://github.com/mAAdhaTTah/wordpress-github-sync/issues/122#issuecomment-166002539)

It works but it's really dirty ;) **I want to override your meta function in external php file (like functions.php or other)** but I don't understand how can I write my function and plug it into the "wpghs_post_meta" filter. 

This is the same for **blob_to_post()** in import.php before set_meta()

Can you show me an example ? 
Thanks a lot

**Comment by mAAdhaTTah** [comment]
If you're trying to add the `myTag` value to the exported meta, you would need to add a filter to the `wpghs_post_meta`:

```php
add_filter( 'wpghs_post_meta', 'add_myTag_to_meta' );

function add_myTag_to_meta( $meta, $post ) {
    $meta['myTag'] = wp_get_post_terms( $post->id, 'myPostType', array( "fields" => "names" ));
    return $meta;
}
```

Obviously, I haven't tested this code, so you'll have to tweak it to make it work for you, but that's the idea.

On the `blob_to_post` side, what are you trying to accomplish? If I understand correctly, you need to then handle the `myTag` value on import. If that's the case, you need to do that on the `wpghs_pre_import_meta` filter. That filter works similarly do the above; write a function that takes the `$meta` and the `$post`, save the `myTag` value into the database, and then return the `$meta` array with the `myTag` key `unset`.

Does that make sense? Let me know if you have any questions.

**Comment by ibenot** [comment]
Thank you very much for you quick reply !
This snippet works perfectly in functions.php when I write a post from Wordpress to Github : 

```
// -----> works perfectly

add_filter( 'wpghs_post_meta', 'add_custom_meta_to_meta' );

function add_custom_meta_to_meta( $meta, $post ) {
    $meta['language'] = wp_get_post_terms(get_the_ID(), 'language', array("fields" => "names"));
    return $meta;
} 
```

But I tried to follow your explanations for the **wpghs_pre_import_meta** filter and it's working with hard-coded values like this (with params = postID, value, myTaxonomie)  : 

```
// -----> works with hard-coded values

add_filter( 'wpghs_pre_import_meta', 'import_custom_meta_to_meta' );

function import_custom_meta_to_meta( $meta, $post ) {
wp_set_post_terms( 354, 'php', 'language' );
}
```
_nb : language is a custom taxonomie
nb2 : with this code, the post #354 is taxonomized with "php" value, and this is the results that I would :)_

With this code, it's broken and import_custom_meta_to_meta does not know post ID and my meta value : 

```
// -----> doesn't work

add_filter( 'wpghs_pre_import_meta', 'import_custom_meta_to_meta' );

function import_custom_meta_to_meta( $meta, $post ) {
wp_set_post_terms( $post->ID, $meta['myTag'], 'language' );
}
```
I tried to add the $blob param but it doesn't work... 
I created **custom post type** with **custom taxonomies** like this : 

`?taxonomy=language&post_type=documentation`

Can you help me ?
Thank you for your help and your time.

**Comment by mAAdhaTTah** [comment]
Two things about this code snippet:

```
add_filter( 'wpghs_pre_import_meta', 'import_custom_meta_to_meta' );

function import_custom_meta_to_meta( $meta, $post ) {
wp_set_post_terms( $post->ID, $meta['myTag'], 'language' );
}
```

1. The `$post` variable is (perhaps inappropriately) not a `WP_Post` object, but a `WordPress_GitHub_Sync_Post` object. It might be a mistake on our part, but the WPGHS_Post object has an `id` property, not an `ID` property. That should probably be changed, cuz that's silly, but for now, use `$post->id`.

2. After you do whatever processing to the `$meta` variable, you need to `unset($meta['myTag']);` so it's no longer in the array and **return the resulting array**. If you don't unset it, the `myTag` value will be saved to `post_meta`, which you don't want, and it's an `add_filter` call, so it's still expecting the resulting array to be returned and processed, so you need to return the remaining array values to be saved into `post_meta`.

Hope that helps!

**Comment by mAAdhaTTah** [comment]
I believe your issue here should been addressed by my previous comment, so I'm going to go ahead and close this issue. If you're still experiencing problems, feel free to reopen.
