### ISSUE TITLE
Query: Can additional folders be created?

### ISSUE THREAD

**Issue by jonocarroll** [mAAdhaTTah/wordpress-github-sync#141]
This is more of a question, but could potentially lead to support required. 

Can we add additional folders to sync'd wpgs repos? I'd like to have a `_data` folder for supplementary material that goes along with some of my posts, and this would allow me to keep the data stored in the same repo as the post itself. My concern is that doing so might break my setup.

Is this (a) safe to do, (b) the best way to go about it?

**Comment by mAAdhaTTah** [comment]
Yes, perfectly safe. You can create whatever files/folders you want in the repo, and WPGHS will ignore any files that don't have YAML frontmatter.
