### ISSUE TITLE
Fatal Error on plugin activation

### ISSUE THREAD

**Issue by staude** [mAAdhaTTah/wordpress-github-sync#142]
The current master brunch generates a fatal error on plugin activation

 Fatal error: Class 'WordPress_GitHub_Sync_Admin' not found in /xxx/wp-content/plugins/wordpress-github-sync/wp-github-sync.php on line 141

**Comment by mAAdhaTTah** [comment]
If you're cloning from GitHub, you need to run `composer install`. If you don't want to use composer, please download the plugin from the [wordpress.org](https://wordpress.org/plugins/wp-github-sync/) repo.

**Comment by staude** [comment]
a ok, i installed it via github updater directly from github into my wordpress.

thank you
