### ISSUE TITLE
Export to GitHub failed with error

### ISSUE THREAD

**Issue by devbanpie** [mAAdhaTTah/wordpress-github-sync#144]
Hi:

I just installed your latest version, set up Github according to your instructions but I get the error: 

Export to GitHub failed with error: Method POST to endpoint https://api.github.com/repos/devbanpie/XgclassBlog/git/trees failed with error: Not Found

I do confirm that https://github.com/devbanpie/XgclassBlog exist and I have made the initial commit. 

Thanks!

**Comment by mAAdhaTTah** [comment]
I see the repo & the API endpoints are returning responses. Can you recheck? Maybe some temp caching issue on the GitHub side right after creating the repo?

**Comment by devbanpie** [comment]
Yes, There is not error message, but the post still did not get synced. btw, could I use localhost with this plugin for test?

**Comment by mAAdhaTTah** [comment]
> btw, could I use localhost with this plugin for test?

Only if your local environment is exposed to the internet. Otherwise, GitHub's webhooks can't hit the site. Checkout out [ngrok](https://ngrok.com/).

**Comment by mAAdhaTTah** [comment]
Is this problem still present?

**Comment by akumar37** [comment]
Facing similar issue.
I am using this plugin but getting error while exporting to Github.
stacktrace -
19-Dec-2016 10:15:58 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to WordPress_GitHub_Sync_Commit::__construct() must be an instance of stdClass, null given, called in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/client/fetch.php on line 45 and defined in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/commit.php:73
Stack trace:
#0 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/client/fetch.php(45): WordPress_GitHub_Sync_Commit->__construct(NULL)
#1 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/client/fetch.php(24): WordPress_GitHub_Sync_Fetch_Client->commit(NULL)
#2 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/export.php(94): WordPress_GitHub_Sync_Fetch_Client->master()
#3 /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/controller.php(158): WordPress_GitHub_Sync_Export->update(13)
#4 /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php(300): WordPress_GitHub_Sy in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/wp-github-sync/lib/commit.php on line 73

-created webhook
- from Github the request response look fine.
-but from wordpress not data getting pushed to git hub.

Please let me know if i am missing something

**Comment by mAAdhaTTah** [comment]
Can you provide the GitHub payload that triggered this error? Don't forget to remove any sensitive info. :)

**Comment by akumar37** [comment]
I think the issue was with the enterprise Git repo that I was using, once i used the public repo on github.com, its working great.
Thanks for the reply.

**Comment by mAAdhaTTah** [comment]
Glad to hear it! I'm going to close this issue, but either of you can reopen if you continue to experience the problem.

**Comment by devbanpie** [comment]
I am still facing this issue. it said:

```
Method GET to endpoint https://api.github.com/repos/username/repo/git/refs/heads/master failed with error: Not Found
```

**Comment by mAAdhaTTah** [comment]
You didn't fill out the settings correctly. You need your actual username &
repo not "username/repo".

On Mar 2, 2018 8:06 AM, "devbanpie" <notifications@github.com> wrote:

I am still facing this issue. it said:

Method GET to endpoint
https://api.github.com/repos/username/repo/git/refs/heads/master
failed with error: Not Found

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/mAAdhaTTah/wordpress-github-sync/issues/144#issuecomment-369945694>,
or mute the thread

**Comment by devbanpie** [comment]
Thanks. I am using the correct usename, this is just for personal information protection. I regenerate the web hook, and it works.But get another problem:

I have those in YAMML section:

```
post_title:  测试文章
post_name: test-articles 
post_date: 2018-01-02 08:00:00
```

when I sync with wordpress, the post date are all changed to the sync time instead of the date specified in the YAML.

**Comment by mAAdhaTTah** [comment]
Related to #191, I think.
