### ISSUE TITLE
is this plugin discontinued?

### ISSUE THREAD

**Issue by JmStudent** [mAAdhaTTah/wordpress-github-sync#147]
I saw some light knowing its existence but last update was 5 months ago from [WordPress Plugin Directory](https://wordpress.org/plugins/wp-github-sync/).

I want to install but... is discontinued?

**Comment by k0nsl** [comment]
@JmStudent: I'm using it for one of my blogs and I have no issues.

**Comment by mAAdhaTTah** [comment]
No, it just hasn't needed an update. If you have issues, feel free to open an issue, but the plugin itself is stable. There are open issues for things I'd like to do, but I've been concentrated on other projects. 

That said, I did get a PR recently for a text update, so I should  update the Readme and publish a new version to the plugin repository.
