### ISSUE TITLE
Preserve `post_date` in Jekyll post on Import

### ISSUE THREAD

**Issue by miklb** [mAAdhaTTah/wordpress-github-sync#148]
I believe I understand how to add tags/categories to the import feature, however what I would like to do is use the `post_date` in the Front Matter of the Jekyll posts, rather than update to the current time when they are imported for published date.

I may have over looked a filter and if I did, if someone can kindly point it out, I would greatly appreciate it.

Thanks!

**Comment by mAAdhaTTah** [comment]
I'm not sure I follow what you're trying to do. Could you explain what the plugin currently does and what you want it to be able to do (expected/actual)?

That said, I think [this issue](https://github.com/mAAdhaTTah/wordpress-github-sync/issues/122) might provide some useful information.

**Comment by miklb** [comment]
Currently, if you add a backdated Jekyll posts to the repo, WordPress sets the publish date as the time it was synced/imported. I would like to use Front Matter that is already in the Jekyll markdown file, `date:`,  to set the publish date in WordPress.

I wasn't sure the filters outlined in that issue could override that.

Sorry wasn't clear and thanks for the reply.

**Comment by mAAdhaTTah** [comment]
I think [`wpghs_pre_import_args`](https://github.com/mAAdhaTTah/wordpress-github-sync/wiki/Customizing-WordPress-GitHub-Sync-with-Filters#wpghs_pre_import_args) is what you're looking for. Found [here](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/database.php#L156) in the code. Feel free to reopen if that doesn't do it for ya.

**Comment by ytjohn** [comment]
@miklb did you ever work out a way to preserve the post date? looking to import an existing static site into wordpress and wanting to automate preserving the dates of the posts.

**Comment by miklb** [comment]
@ytjohn I did not with this plugin. For just importing Jekll into WP, I used import RSS that will import a generated Atom feed from Jekyll. Feel free to ping me on Twitter if can help more.
