### ISSUE TITLE
Error when editing content in Wordpress

### ISSUE THREAD

**Issue by dalareo** [mAAdhaTTah/wordpress-github-sync#149]
I get:

    
    Warning: http_build_query(): Parameter 1 expected to be Array or Object. Incorrect value given in /var/www/html/wp-includes/Requests/Transport/cURL.php on line 507

    Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/Requests/Transport/cURL.php:507) in /var/www/html/wp-admin/post.php on line 197

    Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/Requests/Transport/cURL.php:507) in /var/www/html/wp-includes/pluggable.php on line 1174

**Comment by porkchops1988** [comment]
Who are you and how you know me.

**Comment by mAAdhaTTah** [comment]
@porkchops1988 You replied to a GitHub notification.

@dalareo This seems to be related to the switch to the Requests library in WP 4.6. If there's any chance you can downgrade, that will avoid this error until I can fix the issue.

**Comment by dalareo** [comment]
Thanks! @mAAdhaTTah
