### ISSUE TITLE
Code format: pre lang attribute or markdown format

### ISSUE THREAD

**Issue by victorcuervo** [mAAdhaTTah/wordpress-github-sync#154]
I have a .md file where i use a pre element with a lang attribute.

&lt;pre lang="python"> #Python Code &lt;/pre>

La lang attribute it is not synchronized to the Wordpress article.

In other way if I use the markdown format for code

&grave;&grave;&grave; python
#Python Code
&grave;&grave;&grave;
Convert the content into code elements, but doesn't remove the code language.

&lt;code>python
#Pyhton Code
&lt;/code>

Here I have the .md file that i use for test https://github.com/victorcuervo/manualweb/blob/master/flask/mi-primer-programa-flask.md

Regards.

**Comment by mAAdhaTTah** [comment]
What plugin are you using for Markdown? That's what responsible for translating the backticks. If the plugin you're using doesn't support this syntax, then it'll result in the output you see.

Unfortunately, there isn't anything WPGHS can do about it. I would suggest opening an issue with the Markdown plugin, or switch to a different one.

**Comment by mAAdhaTTah** [comment]
Feel free to comment if you have other questions.
