### ISSUE TITLE
Export to GitHub failed with error

### ISSUE THREAD

**Issue by yanivdll** [mAAdhaTTah/wordpress-github-sync#158]
Installed the plugin in wordpress and followed the documentation step by step.
The repository I'm trying to export into is [https://github.com/yanivdll/wp-prodissues](https://github.com/yanivdll/wp-prodissues).

When trying to do a bulk Export to GitHub, I get the  `Export to GitHub started.` flash message on WP. When refreshing the page I get the following error:

> `Export to GitHub failed with error: Method POST to endpoint https://api.github.com/repos/yanivdll/wp-prodissues/git/trees failed with error: Not Found`

On GitHub, I can see the call to the webhook, with 200 response, but with the following payload:

> `{"success":false,"data":[{"code":"invalid_payload","message":"[Missing Commit ID] won't be imported."}]}`

I see other people with similar issue, but couldn't figure out what was the solution\work-around.

Thanks. Yaniv

**Comment by mAAdhaTTah** [comment]
Yeah, this has popped up before (#144) but I didn't get enough info from the reporters to reproduce. Are there any errors in your logs?

**Comment by yanivdll** [comment]
Sorry if it should be trivial, but where do I find the logs for that plugin?

**Comment by mAAdhaTTah** [comment]
Oh, it just writes to the default WordPress logs. If you have `WP_DEBUG` & `WP_DEBUG_LOG` on, it'll output the logs to `wp-content/debug.log`.

**Comment by yanivdll** [comment]
Thanks. Here's what I get in the log (same as the flash message):
`[03-Feb-2017 03:46:53 UTC] Method POST to endpoint https://api.github.com/repos/yanivdll/wp-prodissues/git/trees failed with error: Not Found`

**Comment by yanivdll** [comment]
Ok, I figured out the problem, and it's on my end. I didn't set the scope of the personal token to public_repo. I realized it has something to do with the credentials because when trying a `GET` call to the url mentioned in the error, I got a `"Bad credentials"` error from GitHub.

**Comment by mAAdhaTTah** [comment]
Oh, good to know. I should update the Readme with some info, since I've gotten this issue before. Glad to hear you got it resolved though.

**Comment by argoncobalt** [comment]
I've been having a similar issue, tried pushing my content to Github and received this:

`Export to GitHub failed with error: Method GET to endpoint https://api.github.com/repos/argoncobalt/site-theme-v001.github.com/git/refs/heads/master failed with error: Not Found`

Any thoughts?

**Comment by mAAdhaTTah** [comment]
@argoncobalt That repo doesn't exist: https://github.com/argoncobalt/site-theme-v001.github.com
Are you trying to export to this repo: https://github.com/argoncobalt/site-theme-v001 ?

**Comment by argoncobalt** [comment]
Yes! I will try again with that.

**Comment by argoncobalt** [comment]
Hmm, I'm still not seeing it there...

**Comment by argoncobalt** [comment]
I hit "Export to Github" but I'm still not seeing anything, should I be doing something else?

**Comment by mAAdhaTTah** [comment]
No errors whatsoever? Anything in the logs?

**Comment by argoncobalt** [comment]
It always just says "Export to Github started" and stays there for a really long time. Not sure how to check the logs.

**Comment by dcc-ca-2018** [comment]
Method GET to endpoint https://api.github.com/repos/dcc-ca-2018/wordpress-ca/git/refs/heads/master failed with error: Bad credentials

**Comment by dcc-ca-2018** [comment]
Any idea? what's wrong?

**Comment by mAAdhaTTah** [comment]
@dcc-ca-2018 You need to fix your GitHub token in the settings page.

**Comment by dcc-ca-2018** [comment]
Ohh hey..! Yeah.. I figured that out and fixed it.. Thanks a million. :)

**Comment by kavithait1996** [comment]
Export to GitHub failed with error: Method GET to endpoint https://api.github.com/repos/kavithait1996/web-backup/git/refs/heads/master failed with error: Git Repository is empty.


same problem...and already i fixed token.

**Comment by mAAdhaTTah** [comment]
@kavithait1996 your repository is empty. You need an initial commit to export to it.

**Comment by thepanesar** [comment]
which option i should select if i have to export to github private repo of my wordpress site using github sync. Thanks in advance

**Comment by Kent152128** [comment]
Here, I got error message "Export to GitHub failed with error: WordPress-GitHub-Sync needs a properly formed repository. Please update your settings." when I export to GitHub.  And my repo setting is right. https://github.com/Kent152128/FIT5120-TP30.git
