### ISSUE TITLE
We couldn’t deliver this payload: Service Timeout

### ISSUE THREAD

**Issue by devmidai** [mAAdhaTTah/wordpress-github-sync#161]
I deploy just like the documentation, But get “We couldn’t deliver this payload: Service Timeout“ error in repo webhook.

**Comment by mAAdhaTTah** [comment]
Best guess is the URL provided in the webhook settings on GitHub is incorrect.

**Comment by devmidai** [comment]
ohh, I use the Enterprise repo. change to personal repo, and it works. thanks!

**Comment by mAAdhaTTah** [comment]
It should support enterprise as well; you would need to update the API endpoint in the plugin's configuration. But if the personal is working for you, go with that! Glad it's working for you.

**Comment by stebrech** [comment]
@mAAdhaTTah I recently get this webhook error and therefore was not able to import.
I tried to remove the webhook and created a new one. The first request was successful, the second right after I pushed a new commit was not. I didn't change any configuration. Then I tried to import a few times. Those requests landed in the nowhere. Do you have any other suggestions than the URL?

<img width="755" alt="bildschirmfoto 2018-03-20 um 21 59 38" src="https://user-images.githubusercontent.com/2923268/37682532-28117718-2c8a-11e8-99ae-00bafdb2f80c.png">

**Comment by sivyel** [comment]
@mAAdhaTTah got response of 400 error and showing webhook body value as 0 instead of error. Do you have any idea ? Previously its working fine.

**Comment by GabrieleCalarota** [comment]
I'm getting this as well

**Comment by mAAdhaTTah** [comment]
@GabrieleCalarota @sivyel I am not actively supporting this plugin (see #193), so I can't be of more help, sorry.

**Comment by tommykye** [comment]
I'm getting this too
