### ISSUE TITLE
how to import post with url set in yaml meta?

### ISSUE THREAD

**Issue by banpie** [mAAdhaTTah/wordpress-github-sync#162]
Hi, I have already use the meta info in my post like:

```
---
layout: post
page_title: aarrr model
date: 2016-10-21 
published: true
permalink: AARRR
tags: [marketing]
---
```

but when I import into WordPress , the WordPress can not recognize the URL that I set in the meta. Is there something wrong with that?

Thanks.

**Comment by mAAdhaTTah** [comment]
The URL in the permalink? e.g.

> permalink: AARRR

And what do you mean by "can not recognize"? Can you specify what you're modifying and what behavior you expect as a result?

**Comment by devmidai** [comment]
Thanks for your reply.

here is the meta in my markdown file named "2016-02-03-增长骇客是什么" (Chinese).

```
---
layout: post
page_title: aarrr model
date: 2016-10-21 
published: true
permalink: AARRR
tags: [marketing]
---
```

Here is what i expect in wordpress post permalink url
```
www.example.com/AARRR
```

but as the result, after I import this markdown file  into wordpress, the post permalink became:

```
www.example.com/%e4%b8%8d%e6%87%82ps%e5%92%8b%e6%8a%a0%e5%9b%be-%e5%b0%8f%e7%99%bd%e6%8a%a0%e5%9b%be%e6%b3%951.
```

**Comment by mAAdhaTTah** [comment]
How did you get the permalink to be "AARRR"? Is that what WP does by default?

**Comment by banpie** [comment]
I set it manually with YAML tag.

**Comment by mAAdhaTTah** [comment]
Oh, the permalink is generated by WordPress and uses the site's url and the post slug. Not sure if there's a way to change the post slug from GitHub yet.

**Comment by mAAdhaTTah** [comment]
Sorry, `post_name` isn't currently editable in that way. The problem is the filename & `post_name` need to stay in sync. If you want to change the permalink, you should edit it in the WP admin.
