### ISSUE TITLE
post categories don't get saved to github

### ISSUE THREAD

**Issue by dirkhh** [mAAdhaTTah/wordpress-github-sync#164]
Maybe I'm doing something wrong again. I use WPML and the Divi theme on my site. Those two, together with this plugin create some fun interactions (basically the idea is that people can translate the website by sending me PRs on github - but of course that usually messes with the post IDs, so there was a bit of a learning curve on what to do where so everything stays sane).

But my actual problem is that the translated posts need to get the translated category. So for example, the English posts are all in "News", the German translations of those posts should be in "Neuigkeiten". Yet it seems that wpghs doesn't actually store the category to GitHub and when it imports the posts back from GitHub, all posts get the "News" category (which is the only English category - just like "Neuigkeiten" is the only German category).

I tried manually storing the category using the wpghs_post_meta and wpghs_pre_import_meta filters, but that failed because when my wpghs_post_meta filter function was called, the $post argument was emptry (??).

Anyway, I realize this is most likely an interaction between the two plugins, but I wonder if someone has an idea how to fix this - right now this really messes with my ability to use this (and it is SO CLOSE to doing exactly what I need).

(for reference: website is subsurface-divelog.org and git repo is at github.com/Subsurface-divelog/subsurface-website -- in the commit history you can see the failed attempts to store categories and you can see the interesting back and forth to get page translations into the right place...)

Thanks

**Comment by dirkhh** [comment]
I think I understand this a bit better now after some more investigation. The problem is mostly WPML related. When we update the database, WPML runs with the default language and the categories of the posts in the other languages aren't visible when WPML isn't running in that language - and so they get dropped. What I think I need is a way to adjust settings in the loop over all the posts that are being updated... I'm trying to figure out what kind of data I would need in order to do this in a clean way...

**Comment by dirkhh** [comment]
Talking to myself here...
I was able to fix this, but it required changes to the database.php file. I guess a generic way to do this would be to add three more actions to save_posts() in database.php:
wpghs_pre_save_loop_action right before the "foreach ( $posts as $post )" loop
wpghs_pre_save_action inside that loop, right at the start (this one needs $post as argument)
wpghs_post_save_loop_action right after the foreach loop
I understand if you'd perceive this as too invasive for a weird special case like this - but this is the only way I can see that wpghs can work with WPML.

**Comment by mAAdhaTTah** [comment]
I'm on vacation. Let me get back to you next week on your suggestion. Feel free to continue to think out loud :).

**Comment by dirkhh** [comment]
I decided to think out loud in the form of a pull request. I still don't know if this is something that you'd consider for the project (in the end, you don't want to add an action or filter in every second line, I guess) - but this is required for me to be able to use wpghs with WPML

**Comment by mAAdhaTTah** [comment]
@dirkhh Do you have this issue worked out?

**Comment by dirkhh** [comment]
Yes - sorry, this time I was traveling.
The solution still feels "hacky", but it works. I have a different issue, though, and will open a new thread for that.

**Comment by litefeel** [comment]
@dirkhh 
try this plugin https://github.com/litefeel/wp-github-sync-meta
