### ISSUE TITLE
Missing Commit ID

### ISSUE THREAD

**Issue by cvharris** [mAAdhaTTah/wordpress-github-sync#170]
The webhook seems to work but nothing gets updated on the site. On digging deeper it appears that the import fails with this:
```
{"success":false,"data":[{"code":"invalid_payload","message":"[Missing Commit ID] won't be imported."}]}
```
However, that seems to be a bad error. The request body clearly has a `head_commit` and `id`. Also, there's nothing in the logs from this other than that error.

What could be the problem?

**Comment by cvharris** [comment]
Found out this was due to the `content-type` of the webhook left to the default`x-www-form-urlencoded`. Seems like we could enhance the error message and check for the content type to bring clarity?

**Comment by mAAdhaTTah** [comment]
Interesting. A more useful error message would definitely be helpful here. I need to give this plugin some love, as there are a few open issues I should address but haven't had time.
