### ISSUE TITLE
Option to Disable tracking ACF fields

### ISSUE THREAD

**Issue by cvharris** [mAAdhaTTah/wordpress-github-sync#171]
I have a page that has several ACF fields with content in them. Exporting to Github, the FrontMatter keeps a lot of the data intact. However, on a push to Github from local changes this sync doesn't handle the custom Repeater field and a few others in ACF, replacing whole chunks of custom fields with and array of strings they can't process.

This plugin would be great if it gave users the option to only sync frontmatter of WP metadata and post/page content.

**Comment by mAAdhaTTah** [comment]
Related to #159. I think I'm going to remove custom meta completely.

**Comment by cvharris** [comment]
Any update on this?

**Comment by mAAdhaTTah** [comment]
@cvharris I haven't had a lot of time to work on this myself. Couple things I'll mention:

1. You can control the [meta exported](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/post.php#L345), so if you're having issues on your site, you should be able to resolve it by filtering it out of the meta array.
2. I'd happily accept a PR to remove that block of code, if you want to update it in the mainline. I do think removing custom meta handling is the way to go, with users explicitly opting in what meta they want to keep beyond the defaults.

**Comment by litefeel** [comment]
@mAAdhaTTah  No effect

**Comment by mAAdhaTTah** [comment]
I haven't released the update yet :)
