### ISSUE TITLE
Not being able to do the initial export.  Repository has an initial commit of readme file

### ISSUE THREAD

**Issue by Techgeekster** [mAAdhaTTah/wordpress-github-sync#173]
This is the error I get when I try to export
Method GET to endpoint https://api.github.com/repos/Techgeekster/BryterWordpress/git/refs/heads/master failed with error: Not Found

**Comment by litefeel** [comment]
https://github.com/Techgeekster/BryterWordpress
this repository cannot found.
You must first create it.

**Comment by Techgeekster** [comment]
It is created.  You cannot see it because it's a private repository

**Comment by litefeel** [comment]
https://github.com/settings/tokens/
make sure your access token allow access private repository.

**Comment by Techgeekster** [comment]
That was it, thank you!

**Comment by mAAdhaTTah** [comment]
@litefeel thanks for the assist!
