### ISSUE TITLE
Feature request: be able to set post_date in frontmatter

### ISSUE THREAD

**Issue by ytjohn** [mAAdhaTTah/wordpress-github-sync#181]
Reason for request: Enables migration from another static blog that uses markdown and frontmatter. 

This is a new issue based on discussions in #140.

Wordpress API lets you set the post_date when you insert a post. This means that you can backdate a post to a prior time.  If post_date is omitted, wordpress will default to the current date and time.

> [You can set the post date manually, by setting the values for ‘post_date’ and ‘post_date_gmt’ keys. You can close the comments or open the comments by setting the value for ‘comment_status’ key.](https://developer.wordpress.org/reference/functions/wp_insert_post/#description)

Even if we set the post_date in frontmatter, WPGHS does not currently read this in and pass it along as an argument to [wp_insert_post](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/def213f89b7df86018bfd4647eca9ae272b03644/lib/database.php#L160). 

In the following example, a test post is created in markdown created with post_date already filled out. WPGHS then injects the post into wordpress with post_date missing (or blank). Wordpress will automatically default to the current date and time and the original markdown file is updated with the new post_date.

```
 ---
 +ID: 511
  post_title: test post 003 ignore
 -post_date: 2017-07-02 21:00:58
 +author: ytjohn
 +post_date: 2017-07-02 21:22:49
 +post_excerpt: ""
  layout: post
 +permalink: >
 +  https://www.yourtech.us/2017/test-post-003-ignore
  published: true
  ---
 -this is a test post for testing wpghs.
 +this is a test post for testing wpghs.
```

**Comment by ytjohn** [comment]
I don't think #180 addresses this, because I want the post_date in wordpress to reflect the date I put in the markdown file. In my original case, I had several years worth of posts from another blog engine with the correct date in the files. I imported these into wordpress and they all got marked as published at the same time. I had to manually go back through wordpress and edit the published date of each post.

**Comment by mAAdhaTTah** [comment]
> I don't think #180 addresses this, because I want the post_date in wordpress to reflect the date I put in the markdown file.

That's correct, this is a separate issue.

I suppose there's no reason offhand why we couldn't make it available. I was just concerned about messing around with the way WordPress sets dates, preferring to let it handle dates itself, which is how we end up with the `post_date` getting reset.

That said, I think you're right, that you should be able to set/modify `post_date` from markdown. Do you know if you have to handle `post_date_gmt` explicitly or will WP handle this correctly for us?

**Comment by mAAdhaTTah** [comment]
Reading your link, looks like we need to handle that explicitly.
