### ISSUE TITLE
GitHub import to Wordpress publishes incorrect date and doesn't auto import after commit

### ISSUE THREAD

**Issue by hellojennifertran** [mAAdhaTTah/wordpress-github-sync#185]
GitHub import to Wordpress publishes incorrect date and doesn't auto import after commit
(Using Wordpress v. 4.8)

**Issues with GitHub > Wordpress Import**

1. When committing a new file, the file doesn't export to Wordpress until I click the "Import from GitHub" link in WordPress (from my understanding, the expectation is that it should auto-import as long as a commit is made whether it's an existing or new published post).
2. When creating a new .md file in GitHub, I leave the date blank in YAML header, and for some reason, the date published in Wordpress will date it as 1970-01-01 rather than real-time date.

**Comment by mAAdhaTTah** [comment]
Yeah, so the second one should definitely default to the current date/time. That's a bug. Surprised that's not how WP works by default.

The first one may not be working if the webhook isn't configured properly.

**Comment by mAAdhaTTah** [comment]
I'll cut a release w/ this fix today or tomorrow.
