### ISSUE TITLE
How does GitHub markdown get converted when displayed on Wordpress?

### ISSUE THREAD

**Issue by hellojennifertran** [mAAdhaTTah/wordpress-github-sync#186]
I'm having issues with GitHub markdown being displayed on Wordpress correctly. The markdown doesn't convert to HTML even after trying WP Markdown plugin. What do you currently use to convert your GitHub markdown? Seems a lot of the markdown converters haven't been maintained/updated.

Thanks for any help!

JT

**Comment by mAAdhaTTah** [comment]
Sorry I missed this the first time around. Did you get this resolved? I currently have a custom implementation using [Markdown-on-Save](https://github.com/roots/markdown-on-save), so I'm not sure how other plugins work.
