### ISSUE TITLE
Document `wpghs_whitelisted_post_types`

### ISSUE THREAD

**Issue by lvnilesh** [mAAdhaTTah/wordpress-github-sync#195]
Thanks for good plugin.

I am able to sync _posts and _pages and want to sync automattic/sensei lessons.

What does it take to sync sensei lessons?

**Comment by mAAdhaTTah** [comment]
Yes, it appears I haven't documented this, but the filter is [here](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/database.php#L293). Use `wpghs_whitelisted_post_types` and return an array of post types you'd like to sync. Defaults to `post` & `page`.

**Comment by lvnilesh** [comment]
simple usage example would be awesome. thank you.

**Comment by mAAdhaTTah** [comment]
Yeah, I changed the title to reflect that, but I'm on vacation now and have other priorities so it may be some time before I get to it.

**Comment by lvnilesh** [comment]
I understand that. Appreciate your help. Take your time.

**Comment by lvnilesh** [comment]
You have documented it already here https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/README.md#custom-post-type--status-support

**Comment by lvnilesh** [comment]
Thank you.
