### ISSUE TITLE
Any way to restore content back to Wordpress?

### ISSUE THREAD

**Issue by nathanmokh** [mAAdhaTTah/wordpress-github-sync#196]
I'm a little confused with how the code interacts with Wordpress, is there any way to download content to restore as if we were using the synced repo as a backup? Currently using this plugin and its great, could be better if I don't have to separately back up content.

**Comment by mAAdhaTTah** [comment]
Yeah, the plugin syncs both ways. See here: https://github.com/mAAdhaTTah/wordpress-github-sync#configuring-the-plugin You need to set up the GitHub webhook, and changes in the repo will be reflected in WordPress.

**Comment by sivyel** [comment]
Draft posts not working both ways,  updating from git to wordpress.

Not working from wordpress to git

**Comment by jeffpaul** [comment]
@sivyel I would consider that expected behavior.  Anything that's on git I'd consider published on the WordPress side of things.

**Comment by mAAdhaTTah** [comment]
There is a filter that you can use to enable syncing drafts, but no, drafts don't sync by default.

**Comment by sivyel** [comment]
Can we have any information about that filter ? Do you have any reference ?

**Comment by mAAdhaTTah** [comment]
The filters are documented in the wiki
