### ISSUE TITLE
Import from github doesn't update but creates a new page

### ISSUE THREAD

**Issue by MixamTheGreat** [mAAdhaTTah/wordpress-github-sync#197]
Hi, 

First of all, thanks for this plugin. It's exactly what I have been looking for and I'm looking forward to contribute in whatever way I can.

I'm importing [this file](https://github.com/MaxVMH/mywebdevresources/blob/master/home.md) in my WordPress installation. Everytime I press import in WordPress, it creates a new page instead of updating the current one. I couldn't find anything about updating existing pages in the Wiki.

Is this a bug? Is it expected behavior? Am I missing something in my file?

**Comment by MixamTheGreat** [comment]
@mAAdhaTTah I found your writing repository and looked at the header, looks like I needed to set an ID.

Looks like this can close :)

**Comment by mAAdhaTTah** [comment]
Glad you ever able to solve it! Let me know if you have other problems.

**Comment by MixamTheGreat** [comment]
Well, I was wondering if is possible to disable comments for a post or page in GitHub before syncing to WordPress, or is it something I should do in WordPress?

Also, should I keep track of ID's myself or is there another way to automatically assign them?

If there is a more appropriate way of asking about these things (support forum?), let me know ;)

**Comment by mAAdhaTTah** [comment]
> Well, I was wondering if is possible to disable comments for a post or page in GitHub before syncing to WordPress, or is it something I should do in WordPress?

GitHub has issues, which you can disable. You don't really comment on "files" on GitHub, but you can comment on commits. Obviously, you can disable comments in WordPress, but that has no impact on GitHub.

> Also, should I keep track of ID's myself or is there another way to automatically assign them?

When you publish a new post on WordPress and export it, it will be exported with the post id. If you create the post in the repo and commit it to GitHub, the syncing process _should_ import the post the update the file with the post ID.

> If there is a more appropriate way of asking about these things (support forum?), let me know ;)

This is fine, I don't have a specific support forum or anything :).

**Comment by MixamTheGreat** [comment]
> GitHub has issues, which you can disable. You don't really comment on "files" on GitHub, but you can comment on commits. Obviously, you can disable comments in WordPress, but that has no impact on GitHub.

What I mean if there is something like `allow_comments: false` to set in the header of a GitHub file so that when it syncs to WordPress, comments are disabled in WordPress.

> When you publish a new post on WordPress and export it, it will be exported with the post id. If you create the post in the repo and commit it to GitHub, the syncing process should import the post the update the file with the post ID.

OK, I figured out what went wrong on my side: the access token didn't have control of the repo which meant that there was no sync going on (I only imported the GitHub repo into WordPress).
