### ISSUE TITLE
Unable to backup Private Posts?

### ISSUE THREAD

**Issue by mashirozx** [mAAdhaTTah/wordpress-github-sync#199]
Some posts I'm working on is in a private status, but seems these private posts unable to sync via this plugin?

**Comment by mAAdhaTTah** [comment]
Use the `wpghs_whitelisted_post_statuses` filter as defined [here](https://github.com/mAAdhaTTah/wordpress-github-sync/blob/master/lib/database.php#L302).

**Comment by mashirozx** [comment]
Do you mean I got to modify this plugin directly?

**Comment by mAAdhaTTah** [comment]
No, use a WordPress filter. And actually, I just remembered this is documented in the README [here](https://github.com/mAAdhaTTah/wordpress-github-sync#custom-post-type--status-support), which has some example code.

**Comment by mashirozx** [comment]
Got it，thank you
