### ISSUE TITLE
Private Repo?

### ISSUE THREAD

**Issue by cmadland** [mAAdhaTTah/wordpress-github-sync#202]
Is it possible to use WPGHS to connect to a private repo?

**Comment by mAAdhaTTah** [comment]
Yup! When you get the GitHub token, make sure it has access to private repos. Otherwise, no other special configuration required.

**Comment by sivyel** [comment]
How to access images from private repo. If we added images in post content from private repo we cannot see those images in frontend is there any way to import images into wordpress and then url change.

**Comment by mAAdhaTTah** [comment]
@sivyel The images should be hosted on the WordPress site. They're not exported to GitHub so there's no special configuration needed.
