### ISSUE TITLE
Class not found?

### ISSUE THREAD

**Issue by ExiaDM** [mAAdhaTTah/wordpress-github-sync#205]
I cant activate the plugin, and got this error:

( ! ) Fatal error: Class 'WordPress_GitHub_Sync_Admin' not found in C:\wamp64\www\mytest\wp-content\plugins\wordpress-github-sync-master\wp-github-sync.php on line 155

**Comment by mAAdhaTTah** [comment]
Where did you download the plugin from? If you cloned down the repository, you'll need composer. Otherwise, download it from WordPress.org or the GitHub releases page, which will ship with the autoloader required to find the class built-in.
