### ISSUE TITLE
Folder Name Should (or Should Not) Be Translated

### ISSUE THREAD

**Issue by mAAdhaTTah** [mAAdhaTTah/wordpress-github-sync#90]
Source: https://wordpress.org/support/topic/_posts-should-not-get-translated

**Comment by mAAdhaTTah** [comment]
I'm crossing posting this here because I'd love to get more opinions on this:

Issue from Aristeides Stathopoulos:

> Hey there!

> Amazing work with this plugin...
> There's just 1 thing:
> on non-english sites, the posts & pages should not be translated. THis way, on github they could still be _posts
> See this for example: https://github.com/ekorinthos/ekorinthos
> The post-types get translated which makes it impossible to use it for a Jekyll site for example..

I originally thought this would be a pretty simple change, but once I started playing around with it, I changed my mind:

> Here's the issue: We're using the post_type_object properties, as found here:

> https://codex.wordpress.org/Function_Reference/get_post_type_object

> Specifically, the object's Label -> Name property. This property allows us to get the plural name for a particular post type; in the default case, "Posts", which is translated based on the current WordPress language. We can't use the post_type slug (which would be "post" in that case), since it's not plural, and the folder should be "_posts"; we also can't assume adding an "s" to the end of the post_type makes it plural because English.

> There are filters you can use to set the folder name: wpghs_directory_published and wpghs_directory_published. You can see documentation for the filters here:

> https://github.com/benbalter/wordpress-github-sync/wiki/Customizing-WordPress----GitHub-Sync

> So you can reset your directory name to whatever you'd like, to ensure it works with the language you're using. If you have any questions about the filters, let me know.

> The other option is to add an additional conditional, that says if post_type == 'post', then we use '_posts', and fall back to the Label -> Name property for non-post post_types. However, this forces everyone to use the English folder names, rather than the WordPress installation language.

> FWIW, I think this should actually go the other way, and translate all of the folder names, which means localizing the _drafts folder as well, and if you need to make sure your installation works with Jekyll, the plugin should be flexible enough to make this possible.

> However, I'm new to dealing with i18n issues, so if you disagree, let me know what you think.

**Comment by benbalter** [comment]
So the question is whether the folder name `_posts` should be consistent or translated depending on the language of the WP site? 

I'd argue that the folder name should remain constant for two reasons:

1. The `_posts` folder is intended to be machine readable, or at the very least scriptable. Whether or not we want things to be Jekyll-compatible going forward is going to be up to @mAAdhaTTah, but being able to go into a repo and knowing where posts are outside the WP environment (which wouldn't have the translation) is a big enabler of using WP content elsewhere.

2. Internally, WP uses the `posts` table, and the `post` content type, even for developer interfaces (despite the UI being translated). Again, I can jump into any WP install and know where posts are. The same can and should be able to be said of the corresponding git repo. I suspect 99% of the git use is going to be by either machines or by technical humans that can navigate the single `_posts` folder, even if it's not translated. 

Put another way, you get an entire machine-readable workflow by a predictable folder naming structure, a workflow that allows you to use WordPress content in all sorts of non-WordPress ways, but only gain a slightly more intuitive git-based UI (which I suspect isn't the primary UI for most users) by translating it.

**Comment by drallgood** [comment]
I agree. Folders should not be translated.

**Comment by mAAdhaTTah** [comment]
@drallgood @benbalter Thanks for the feedback. I'll go with untranslated folders then. I'll add unit tests for the method, merge in the PR, and push up a new version tonight.
